### PR TITLE
Create 35. Search Insert Position.cpp

### PR DESCRIPTION
**Pull request by Unknown-hunk**

### CODE REVIEW

**Comment by Keerat666** [comment]
Hey @Unknown-hunk 

The code throws up an error while validating on Leetcode.

Please check your function signature for bugs. The correct one might be : 

```
 int searchInsert(vector<int>& nums, int target) {
```
Feel free to fix it in another commit and I would merge it!

**Comment by Unknown-hunk** [comment]
@Keerat666 Please check... done with the changes

**Comment by Keerat666** [comment]
Hey @Unknown-hunk 

The code works perfectly fine, but can you please put it inside a folder called 35-SearchInsetPosition.

**Comment by Unknown-hunk** [comment]
Can u please check once if its done or not... @Keerat666

**Pull request merged**
