### PR TITLE
Create find_minimum_in_rotated_sorted_array_ii.cpp

### PR DESCRIPTION
**Pull request by shrivardha**
#Issue 57
Link: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/

### CODE REVIEW

**Comment by shrivardha** [comment]
Hi.. I have done the necessary commits. This is my 1st PR. Please help if i am wrong!

**Comment by Keerat666** [comment]
Hey @shrivardha 

The code looks good to go. But can you just move this file to a folder in the leetcode-hard folder.
- You can Create a folder called 154-MinRotatedArraySort-2 inside Leetcode hard.
- Move the solution from the root directory to this folder (154-MinRotatedArraySort-2) and make another commit

Will then merge it at the earliest once this is done 💯 
Thanks a lot in advance!

**Comment by shrivardha** [comment]
> 

done!

**Comment by Keerat666** [comment]
> done!

PR Merged 🚀

**Comment by shrivardha** [comment]
Thanks a lot!

**Pull request merged**
