### PR TITLE
15. 3Sum.java

### PR DESCRIPTION
**Pull request by KCoder29**

### CODE REVIEW

**Comment by KCoder29** [comment]
Please mark my commit as hacktober-fest accepted.

**Comment by Keerat666** [comment]
Hey @KCoder29 

Please fix the folder structure for this one as well and make another commit.

**Comment by KCoder29** [comment]
Please merge my new commit I have fixed the folder name. Please mark my commit as hacktober-fest accepted.

**Comment by Keerat666** [comment]
@KCoder29 I can't see your solution in the latest commit

**Comment by Keerat666** [comment]
Please reopen this or drop a comment to reopen this PR once you are ready!

**Pull request closed without merging**
