### PR TITLE
Create Soution.java

### PR DESCRIPTION
**Pull request by im-anahata**

### CODE REVIEW

**Comment by Keerat666** [comment]
Hey @im-anahata 

Can you please create an issue for this before I merge it?

Thanks in advance.

**Comment by im-anahata** [comment]
Okay

**Comment by im-anahata** [comment]
I had created an issue hope you would merge the solution now

**Comment by Keerat666** [comment]
> I had created an issue hope you would merge the solution now

Done bro 💯 
Thanks for the contribution!

**Pull request merged**
