### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Harshdev625**
Added 1528 Shuffle String Leetcode Problem in C++ Language.

### CODE REVIEW

**Comment by Keerat666** [comment]
@Harshdev625 would be happy to merge your code but please fix these issues

- Please create an issue for this 
- Fix the folder path 

Please check this https://github.com/Keerat666/LeetCode-HacktoberFest22/discussions/141

**Comment by Keerat666** [comment]
Hey @Harshdev625 

I can't see the issue for this problem.

And the path is still incorrect.

**Comment by Harshdev625** [comment]
Sir/Ma’am,                   I am new to this platform can you please guide me on how to do that? Sent from Mail for Windows From: Gurkeerat SinghSent: 12 October 2022 01:35To: Keerat666/LeetCode-HacktoberFest22Cc: HARSH DEV; MentionSubject: Re: [Keerat666/LeetCode-HacktoberFest22] Add files via upload (PR #187) Hey @Harshdev625I can't see the issue for this problem.And the path is still incorrect.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Harshdev625** [comment]
Sir/Ma’am48. Rotate Image · Issue #191 · Keerat666/LeetCode-HacktoberFest22 (github.com)This is the issue I created. Sent from Mail for Windows From: Gurkeerat SinghSent: 12 October 2022 01:35To: Keerat666/LeetCode-HacktoberFest22Cc: HARSH DEV; MentionSubject: Re: [Keerat666/LeetCode-HacktoberFest22] Add files via upload (PR #187) Hey @Harshdev625I can't see the issue with this problem.And the path is still incorrect.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Keerat666** [comment]
Please read this : 

https://www.earthdatascience.org/workshops/intro-version-control-git/basic-git-commands/

Uploading directly from github is not a very optimised way of pushing your code. 

Once you figure out a way to push code from cmd, then make the required changes for the folder path.

**Comment by Harshdev625** [comment]
Sir/Maam I have changed the folder path.

**Pull request closed without merging**
