### PR TITLE
Solution for letter-combinations-of-a-phone-number

### PR DESCRIPTION
**Pull request by sivasuriyankumarasamy**

### CODE REVIEW

**Comment by sivasuriyankumarasamy** [comment]
https://leetcode.com/problems/letter-combinations-of-a-phone-number/

**Comment by Keerat666** [comment]
@sivasuriyankumarasamy 

Would be glad to merge your code but can you please move your file to the correct folder and do another commit?
Also create an issue for this so that other people can contribute to this problem as well.

https://github.com/Keerat666/LeetCode-HacktoberFest22/discussions/141

**Comment by sivasuriyankumarasamy** [comment]
Hi @Keerat666,

I have updated my file name and created an issue.

Kindly review. Thanks

**Comment by Keerat666** [comment]
Done 👍 
Thanks for contributing!

**Pull request merged**
