### PR TITLE
Create longest_common_prefix.cpp

### PR DESCRIPTION
**Pull request by Soumyajit2825**
#9 solved

### CODE REVIEW

**Comment by Keerat666** [comment]
Hey @Soumyajit2825,

Can you please create a folder called 14-LongestCommonPrefix and inside it put your solution file and do another commit in order for me to merge it?

**Comment by Soumyajit2825** [comment]
ok sure

**Comment by Soumyajit2825** [comment]
done check now

**Comment by Keerat666** [comment]
Already merged!

**Comment by Soumyajit2825** [comment]
Thanks!

**Pull request closed without merging**
